openMF/ph-ee-importer-es

.github/workflows/test.yml

Working as indicated here https://github.com/afk11/ph-ee-importer-es/actions/runs/1708974260

Add Github Actions workflow to check project can be packaged

---

.gitignore
build.gradle
src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticClient.java
src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchTemplateSetup.java
src/main/java/hu/dpc/rt/kafkastreamer/importer/KafkaImporter.java

Updating ES java Client

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticClient.java

Adding log statements

---

src/main/resources/zeebe-record-deployment-template.json
src/main/resources/zeebe-record-incident-template.json
src/main/resources/zeebe-record-job-template.json
src/main/resources/zeebe-record-process-instance-template.json
src/main/resources/zeebe-record-process-template.json
src/main/resources/zeebe-record-variable-document-template.json
src/main/resources/zeebe-record-variable-template.json

Updating static mappings files

---

src/main/resources/zeebe-record-deployment-template.json
src/main/resources/zeebe-record-incident-template.json
src/main/resources/zeebe-record-job-template.json
src/main/resources/zeebe-record-process-instance-template.json
src/main/resources/zeebe-record-process-template.json
src/main/resources/zeebe-record-variable-document-template.json
src/main/resources/zeebe-record-variable-template.json

Updating json for static mapping

---

build.gradle
src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticClient.java
src/main/resources/zeebe-record-deployment-template.json
src/main/resources/zeebe-record-incident-template.json
src/main/resources/zeebe-record-job-template.json
src/main/resources/zeebe-record-process-instance-template.json
src/main/resources/zeebe-record-process-template.json
src/main/resources/zeebe-record-variable-document-template.json
src/main/resources/zeebe-record-variable-template.json

Updating json file

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticClient.java
src/main/resources/zeebe-record-deployment-template.json
src/main/resources/zeebe-record-incident-template.json
src/main/resources/zeebe-record-job-template.json
src/main/resources/zeebe-record-process-instance-template.json
src/main/resources/zeebe-record-process-template.json
src/main/resources/zeebe-record-variable-document-template.json
src/main/resources/zeebe-record-variable-template.json

Updating json file for including dynamic mapping

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticClient.java
src/main/resources/zeebe-record-variable-template.json

Updating put template request

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticClient.java

Updating index template version

---

.gitignore
src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java

@avikganguly01 : Please review the logic.

Changing data type of process instance to string

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java

@avikganguly01 : Please review and merge
Minor fix fro changeing instance id data type from long to string

Updating logic for converting instance id from long to string

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java

@avikganguly01 : please review and merge
Minor fix for updating data type for instance id

Updating the value for instance id

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java

@avikganguly01 : Please Review and Merge

Minor Fix: For updating the data type of instance Id

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java

Adding Logic For Composable Template
[Code doesn't has any compilation error]
@avikganguly01 : Please review and merge

Updating composable template

---

build.gradle
src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java

Data Type to change the index template to composable template.
@avikganguly01 : Please Review

Updating data type for Composable Template

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java

@avikganguly01 : please review

Creating new Index for Zeebe Variables

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java

@avikganguly01 
Please review merge
Contains changes: 
Added settings for new template
Removed data modification of phone number
Changed timestamp datatype

Creating document for zeebe variables in kibana 1

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java
src/main/resources/application.yml

Adding flag to disable reporting index.
@avikganguly01 : Please Review
Related PRs:
https://github.com/fynarfin/ph-ee-env-template/pull/74
https://github.com/fynarfin/ph-ee-env-labs/pull/58

Adding flag to disable new Reporting Index

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java
src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchTemplateSetup.java
src/main/resources/zeebe-payments.json

The PR includes the following changes: 
1. Data type of Amount changes
2. Double quotes removed from strings
3. Process Instance key sent as text
4. Adding alias for zeebe payments
5. Reducing number of indices. Process, Process instance, variable, incident and payments
6. Adding static mapping for new index

adding minor chnages

---

src/main/resources/zeebe-payments.json

adding dynamic template in json

---

src/main/resources/zeebe-payments.json

updating dynamic template in mapping json

---

src/main/java/hu/dpc/rt/kafkastreamer/importer/ElasticsearchClient.java
src/main/resources/zeebe-payments.json
src/main/resources/zeebe-record-deployment-template.json
src/main/resources/zeebe-record-error-template.json
src/main/resources/zeebe-record-incident-template.json
src/main/resources/zeebe-record-job-batch-template.json
src/main/resources/zeebe-record-job-template.json
src/main/resources/zeebe-record-message-subscription-template.json
src/main/resources/zeebe-record-message-template.json
src/main/resources/zeebe-record-template.json
src/main/resources/zeebe-record-variable-document-template.json
src/main/resources/zeebe-record-variable-template.json
src/main/resources/zeebe-record-workflow-instance-creation-template.json
src/main/resources/zeebe-record-workflow-instance-subscription-template.json
src/main/resources/zeebe-record-workflow-instance-template.json

This PR contains :
1. Custom mapping for different indices
2. Logger statements for version logging
@avikganguly01 : Please Review and Merge

Adding custom mapping and logs

---

src/main/java/org/mifos/phee/kafkastreamer/importer/ElasticsearchClient.java
src/main/java/org/mifos/phee/kafkastreamer/importer/ElasticsearchTemplateSetup.java
src/main/java/org/mifos/phee/kafkastreamer/importer/ExtendedValueType.java
src/main/java/org/mifos/phee/kafkastreamer/importer/KafkaConfiguration.java
src/main/java/org/mifos/phee/kafkastreamer/importer/KafkaElasticImportApplication.java
src/main/java/org/mifos/phee/kafkastreamer/importer/KafkaImporter.java
src/main/resources/zeebe-record-workflow-instance-template.json

This PR has the following changes 
1. Renaming of PAckages
2. Workflow instance changed to accomodate Process instance pushes
3. Mapping for process instance index added to workflow instance
4. additional logs
@avikganguly01 : Please review

Replacing the process instance with workflow and renaming package

---

src/main/java/org/mifos/phee/kafkastreamer/importer/ElasticsearchClient.java
src/main/resources/application.yml

This PR has changes for enabling importer es connect to Es after Es Security upgrade
@avikganguly01 @fynmanoj

Added code for es security

---

src/main/java/org/mifos/phee/kafkastreamer/importer/ElasticsearchClient.java
src/main/java/org/mifos/phee/kafkastreamer/importer/PaymentsIndexConfiguration.java
src/main/resources/application.yml

Following PR contains customisable list of fields for new reporting index. 
Related PRs:
https://github.com/fynarfin/ph-ee-env-template/pull/92
https://github.com/fynarfin/ph-ee-env-labs/pull/71
@avikganguly01 @fynmanoj : Please review

Adding customisable fields for reporting index

---

src/main/resources/application.yml
src/main/resources/zeebe-payments.json

Adding variable support for clientCorrealtionId and ams name with enable/disable options.

Adding new variable support in reporting index

---

src/main/resources/zeebe-payments.json

This to fix the issue:
`Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [https://ph-ee-elasticsearch:9200], URI [/_template/zeebe-payments?master_timeout=30s&include_type_name=true], status line [HTTP/1.1 400 Bad Request]
Warnings: [Legacy index templates are deprecated in favor of composable templates., [types removal] Specifying include_type_name in put index template requests is deprecated. The parameter will be removed in the next major version.]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [ams]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: No handler for type [string] declared on field [ams]","caused_by":{"type":"mapper_parsing_exception","reason":"No …

Updating data type for bug fix

---

src/main/resources/application.yml
src/main/resources/zeebe-payments.json

- Added custom data,currency and error information variables to reporting index

Added variables to reporting index

---

src/main/java/org/mifos/phee/kafkastreamer/importer/ElasticsearchClient.java
src/main/java/org/mifos/phee/kafkastreamer/importer/PaymentsIndexConfiguration.java
src/main/resources/application.yml

- custom data configuration level and code level

Custom data field

---

src/main/java/org/mifos/phee/kafkastreamer/importer/ElasticsearchClient.java
src/main/java/org/mifos/phee/kafkastreamer/importer/PaymentsIndexConfiguration.java
src/main/resources/application.yml

- changed custom data level
- added client correlation id

Changed custom data level

---

src/main/java/org/mifos/phee/kafkastreamer/importer/ElasticsearchClient.java
src/main/java/org/mifos/phee/kafkastreamer/importer/PaymentsIndexConfiguration.java
src/main/resources/application.yml

- custom data field
- reporting variables

Custom data new fields

---

build.gradle
src/main/java/org/mifos/phee/kafkastreamer/importer/KafkaImporter.java
src/main/java/org/mifos/phee/kafkastreamer/importer/KafkaVariables.java
src/main/java/org/mifos/phee/kafkastreamer/importer/service/MaskingService.java
src/main/java/org/mifos/phee/kafkastreamer/importer/service/MaskingServiceImpl.java
src/main/java/org/mifos/phee/kafkastreamer/importer/utils/AesUtil.java
src/main/resources/application.yml

* Implemented AES encryption on sensitive data. 
* Added the configuration for secret and fields which is to be encrypted.
Refer [this](https://mifosforge.jira.com/browse/GOV-292) jira for more info.

GOV-292: Implemented the masking service and integrated it

---

.circleci/config.yml

(https://mifosforge.jira.com/browse/GOV-527) Description
* CircleCI pipeline updated to build and push the docker image to docker hub 
* Add a link to the design document or include the design bullet points related to this PR here.

#GOV-527 Docker Image Build and Push to DockerHub

---

src/main/java/org/mifos/phee/kafkastreamer/importer/ElasticsearchClient.java
src/main/java/org/mifos/phee/kafkastreamer/importer/service/MaskingServiceImpl.java
src/main/java/org/mifos/phee/kafkastreamer/importer/utils/AesUtil.java
src/main/resources/zeebe-payments.json

- Resolved flush issue
- Increased AES Length
- Null check for masking code
https://fynarfin.atlassian.net/browse/PHEE-384?atlOrigin=eyJpIjoiY2IxYzQyOGFkY2EzNGUyMTk3N2IzNzdiMWQyZjcyMDEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ

[PHEE-384] Resolved flush issue and null checker for payer and payee 
